### ISSUE TITLE
Request code to add copy function

### ISSUE THREAD

**Issue by mq00fc** [leafee98/hugo-theme-flat#2]
Hello, when I use 
```c#
Console.WriteLine("hello")
```
 it cannot be copied automatically. If it is possible, can you add this function? Thank you

**Comment by leafee98** [comment]
A button shown on top-right of the code area to copy all text in this area, like the GitHub one?

![image](https://github.com/leafee98/hugo-theme-flat/assets/32585295/b78796cb-1b6b-4aa1-b73c-99138e653baa)

I will give it a try :)

**Comment by mq00fc** [comment]
> A button shown on top-right of the code area to copy all text in this area, like the GitHub one?
> 
> ![image](https://private-user-images.githubusercontent.com/32585295/346440913-b78796cb-1b6b-4aa1-b73c-99138e653baa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MTgwODEsIm5iZiI6MTcyMDQxNzc4MSwicGF0aCI6Ii8zMjU4NTI5NS8zNDY0NDA5MTMtYjc4Nzk2Y2ItMWI2Yi00YWExLWI3M2MtOTkxMzhlNjUzYmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA1NDk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyYTVhNDhiMzQ0NGI4MjllZDYxNzkxMzA1ZTk2NDEyN2MxYWM4ZDZlYzAzYjE5MzQ5ODlhZTVlMGEyMGRhODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zP2PIeaFH2OFxAHF3So56zJfxMuyWTpTYM6veUTmgsI)
> 
> I will give it a try :)

yes,like this

thanks!谢谢
